# defaults
TOP ?= ..
ARMIPS ?= $(TOP)/armips.exe

# Set some stuff
PNACH_CRC = SCUS-97248_5F3A6BC0
PNACH_NAME = debug_menu

MAIN_BINARY = debug_menu_patch.bin
SOURCE_FILE = debug_menu.asm

include $(TOP)/make/rules.mk