# defaults
TOP ?= ..
ARMIPS ?= $(TOP)/armips.exe

# Set some stuff
PNACH_CRC = 96848841
PNACH_NAME = no_autoreset

MAIN_BINARY = no_autoreset_patch.bin
SOURCE_FILE = no_autoreset.asm

include $(TOP)/make/rules.mk